apiVersion: v1
kind: Service
metadata:
  name: tk-docs-service
  labels:
    app: tk-docs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tk-docs
---
# Optional: NodePort service for direct access (development/testing)
# Uncomment if you want to access the app via NodeIP:NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: tk-docs-nodeport
#   labels:
#     app: tk-docs
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 3000
#     nodePort: 30080  # Access via <NodeIP>:30080
#     protocol: TCP
#     name: http
#   selector:
#     app: tk-docs
